### PR TITLE
Readme Update and All Contributors Guidelines Adoption

### PR DESCRIPTION
**Pull request by EiffL**
This PR aims to slightly update our messy readme, with the pretty AI generated picture made by @ConnorStoneAstro , and I'm raising the question of whether we want to adopt All Contributors, which I would then be happy to implement.

### CODE REVIEW

**Comment by EiffL** [comment]
Are you ok with using that image on the README @ConnorStoneAstro ?

**Comment by ConnorStoneAstro** [comment]
> Are you ok with using that image on the README @ConnorStoneAstro ?

That works for me! Glad you liked it :)

**Comment by EiffL** [comment]
Let me know what you think @Smith42 , if all looks good we can merge

**Comment by Smith42** [comment]
Looks like we need to install the all contributors bot to get it working fully. I put in a request, but don't think I have access to approve, @EiffL do you have access to check the "@AstroPile" account notifications?

Screenshot 2024-05-29 at 23 27 51

**Comment by EiffL** [comment]
Done :-)

**Review by Smith42 — APPROVED** [review]

**Comment by EiffL** [comment]
@all-contributors please add @Smith42 for infrastructure

**Comment by EiffL** [comment]
hehehehehe :-)

**Comment by Smith42** [comment]
that's so cool!

**Comment by Smith42** [comment]
@all-contributors please add @EiffL for infrastructure

**Pull request merged**
